#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=8g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx4g
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.tooling.parallel=true

kotlin.mpp.enableCInteropCommonization=true
compose.resources.always.generate.accessors=true


#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
buildkonfig.flavor=dev

#Native
kotlin.native.binary.gc=cms
kotlin.native.binary.smallBinary=true
kotlin.incremental.native=truee